"""
generate_wltp_csv.py — helper script to produce stimuli/wltp_discharge.csv
Run once at project setup if the CSV needs regeneration.

The reference SOC is generated by running the actual BMSModel so that
TC_001 has a realistic but achievable tracking target.
"""
import csv
import math
import os
import random
import sys

# Allow importing the MUT when run from within pyxil_bms/
_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)   # Repo root
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from mut.bms_model import BMSModel  # noqa: E402

random.seed(42)

OUTPUT_PATH = os.path.join(_HERE, "wltp_discharge.csv")
N_ROWS = 300
DT_S = 60.0  # seconds per data row (each row = one 60-second interval)

# SOC: generated by model, expected to start ~95% and end ~25-35%
_INITIAL_SOC = 95.0


def _wltp_current(t: float) -> float:
    """Synthetic WLTP-like current [A]. Negative=discharge, positive=regen."""
    # Base discharge
    base = -55.0
    # Low frequency oscillation (speed phases)
    wave1 = -35.0 * math.sin(2 * math.pi * t / 7200.0)
    # Regen braking spikes (every ~1800s)
    regen = 35.0 if (int(t / DT_S) % 30 == 0) else 0.0
    # High-freq noise
    noise = random.gauss(0, 4.0)
    current = base + wave1 + regen + noise
    return max(-120.0, min(40.0, current))


def _voltage_from_soc_and_current(soc: float, current: float) -> float:
    """
    Terminal voltage: V = OCV(SOC) + R_internal * current
    (current < 0 during discharge → voltage sag below OCV)
    """
    # OCV rough linear model: 3.2V at 0% → 4.11V at 100%
    ocv = 3.2 + (soc / 100.0) * 0.91
    r_internal = 0.002   # Ω (total pack internal resistance)
    v_terminal = ocv + r_internal * current  # current < 0 → voltage drops
    return max(3.0, min(4.4, v_terminal))


# ---------------------------------------------------------------------------
# Generate profile by running BMSModel to produce realistic reference SOC
# ---------------------------------------------------------------------------
model = BMSModel(initial_soc_pct=_INITIAL_SOC, timestep_s=DT_S)
rows = []

for i in range(N_ROWS):
    t = float(i) * DT_S
    current = _wltp_current(t)
    # New model uses _soc_pct as internal raw SOC
    soc_prev = model._soc_pct

    voltage = _voltage_from_soc_and_current(soc_prev, current)
    temp = 25.0 + 3.0 * math.sin(2 * math.pi * t / 18000.0)

    # Step the model with the stimulus
    inputs = {
        "pack_current_A": current,
        "pack_voltage_V": voltage * 6, # Pack voltage for 6 cells
        "cell_voltages": [voltage] * 6,
        "cell_temperatures": [temp] * 6,
        "capacity_Ah": 100.0,
    }
    outputs = model.step(inputs)

    # Reference SOC = this step's post-step output from the model
    soc_ref = outputs["SOC_estimated"]

    rows.append({
        "time_s": f"{t:.1f}",
        "current_A": f"{current:.4f}",
        "voltage_V": f"{voltage:.4f}",
        "temperature_C": f"{temp:.4f}",
        "SOC_reference": f"{soc_ref:.4f}",
    })

with open(OUTPUT_PATH, "w", newline="", encoding="utf-8") as fh:
    writer = csv.DictWriter(
        fh, fieldnames=["time_s", "current_A", "voltage_V", "temperature_C", "SOC_reference"]
    )
    writer.writeheader()
    writer.writerows(rows)

final_soc = float(rows[-1]["SOC_reference"])
print(f"Generated {N_ROWS} rows → {OUTPUT_PATH}")
print(f"  SOC range: {float(rows[0]['SOC_reference']):.2f}% → {final_soc:.2f}%")
